### ISSUE TITLE
Password length check?

### ISSUE THREAD

**Issue by friedhelm-langhof** [sneas/passwordmeter#1]
The password length check doens't work as expected. If an password is too short its gets also a score. If this score is higher than a number its maybe valid.

**Comment by sneas** [comment]
As description says, the intention of the project is to provide unobtrusive password checker based on http://www.passwordmeter.com/. Which considers password length in it's own way. (Ex: type '123' and you'll see 4% even though password min length is 8).

To make sure insufficient password length always considers as 0% you can wrap the existing function. Ex:

```
function checkPassword(pwd, len) {
  if (pwd.length < len) {
    return 0;
  }

  return passwordMeter.checkPass(pwd, len);
}
```

**Comment by friedhelm-langhof** [comment]
I solved this issue different. But i recommend to either move this code to your package or write sth like this to the readme.
